[project]
name = "ersteinvestment"
version = "0.1.0"
description = ""
authors = [
    {name = "zolcsika71",email = "bushdoctor2008@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "argparse (==1.4.0)",
    "pandas (==3.0.4)",
    "python-calamine (>=0.3.0)",
    "xlrd (>=2.0.2,<3.0.0)",
    "scipy (==1.18.0)",
    "xgboost (==3.3.0)",
    "openai (==2.48.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
